version: "3.8"

services:
  api:
    build: images/server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI:
      API_PORT:

  web:
    build: images/client
    ports:
      - "5173:5173"
    volumes:
      - ./images/client/src:/app/src
      - ./images/client/public:/app/public
      - ./images/client/index.html:/app/index.html
      - ./images/client/vite.config.js:/app/vite.config.js
    environment:
      VITE_API_URL:
      CHOKADIR_USEPOLLING: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./_volumes/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL:
      ME_CONFIG_BASICAUTH_ENABLED:
      ME_CONFIG_BASICAUTH_USERNAME:
      ME_CONFIG_BASICAUTH_PASSWORD:
