services:
  api:
    build: ./images/server
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/PokemonUsers
      API_PORT: ${API_PORT}
    depends_on:
      mongo:
        condition: service_healthy

  web:
    build: ./images/client
    ports:
      - "5173:5173"
    volumes:
      - ./images/client/src:/app/src
      - ./images/client/public:/app/public
      - ./images/client/index.html:/app/index.html
      - ./images/client/vite.config.js:/app/vite.config.js
    environment:
      VITE_API_URL: ${VITE_API_URL}
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - api

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./_volumes/db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      interval: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
    depends_on:
      - mongo
